title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          blocks:
            label: Content Blocks
            type: blocks
            translate: true
  sidebar:
    width: 1/3
    sections:
      files:
        type: files
      settings:
        type: fields
        fields: