title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          blocks:
            label: Content Blocks
            type: blocks
            translate: true
  sidebar:
    width: 1/3
    sections:
      files:
        type: files
      settings:
        type: fields
        fields:
          showInMenu:
            label: Show in Menu
            help: If checked, this page will be displayed in the main menu.
            type: toggle
            translate: false
            default: false       