title: Content

tabs:
  events:
    icon: 📅
    columns:
      - width: 2/3
        sections:
          events:
            type: pages
            parent: site.find("events")
            templates:
              - event
            headline: Events
            sortBy: date desc
            limit: 20
            layout: table
            columns:
              date:
                width: 1/6
            # query: site.index(true).filterBy("template", "event").filterBy("recurrence", "none")

      - width: 1/3
        sections:
          recurringEvents:
            type: pages
            parent: site.find("recurring-events")
            templates:
              - recurring-event
            headline: Recurring Events
            limit: 20
            # query: site.index(true).filterBy("template", "event").filterBy("recurrence", "!=", "none")

  pages:
    label: Pages
    icon: 🗂️
    columns:
      - width: 3/3
        sections:
          pages:
            type: pages
            templates:
              - default
              - home
              - faq
              - unterstuetzung
            limit: 20

      # - width: 1/3
      #   sections:
      #     dynamicPages:
      #       type: pages
      #       label: Dynamic Pages
      #       templates:
      #         - posts
      #         - events
      #       limit: 10

  newsletter:
    label: Newsletter
    icon: email
    columns:
      - width: 1/1
        sections:
          newsletterLink:
            type: info
            headline: Newsletter Generator
            text: |
              <div style="padding: 2rem; text-align: center;">
                <p style="margin-bottom: 1rem; color: #777;">Erstelle Newsletter-Entwürfe in Brevo oder sende sie direkt</p>
                <a href="/newsletter-generator" target="_blank" style="display: inline-block; background: #4271ae; color: #fff; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: 600;">
                  📧 Newsletter Generator öffnen
                </a>
              </div>

  configuration:
    icon: cog
    columns:
      - width: 1/3
        sections:
          general1:
            type: fields
            fields:
              menu:
                label: Menu
                type: pages

      - width: 1/3
        sections:
          general2:
            type: fields
            fields:
              # logo:
              #   label: Logo
              #   translate: false
              #   type: files
              #   max: 1
              placeholderImage:
                label: Placeholder Image
                help: This image will be used as a default image, for when no image is uploaded to an event or a page.
                translate: false
                type: files
                max: 1
                size: small

      - width: 1/3
        sections:
          general3:
            type: fields
            fields:
              socialLinks:
                label: Social Links
                type: structure
                translate: false
                fields:
                  name:
                    label: Social Network Name
                    type: text
                  url:
                    label: URL
                    type: url
                  icon:
                    label: Icon
                    type: select
                    options:
                      facebook: Facebook
                      instagram: Instagram
                      youtube: YouTube
          # generateStaticSite:
          #   label: Generate Static Site
          #   type: pages
          #   templates:
          #     - static-site-generator
          #   help: admin use only
