title: Content

tabs:
  events:
    icon: 📅
    columns: 
      - width: 2/3
        sections:
          events:
            type: pages
            headline: Events
            sortBy: date desc
            limit: 20
            layout: table
            columns:
              date:
                width: 1/6
            query: site.index(true).filterBy("template", "event").filterBy("recurrence", "none")

      - width: 1/3
        sections:
          recurringEvents:
            type: pages
            headline: Recurring Events
            limit: 20
            query: site.index(true).filterBy("template", "event").filterBy("recurrence", "!=", "none")

  pages:
    label: Posts & Pages
    # icon: page
    icon: 🗂️
    columns: 
      - width: 2/3
        sections:
          posts:
            type: pages
            parent: site.find("posts")  # get posts from parent page
            templates: 
              - post
            limit: 10

      - width: 1/3
        sections:   
          pages:
            type: pages
            templates: 
              - default
              - home
            limit: 10  
          dynamicPages:
            type: pages
            label: Dynamic Pages
            templates: 
              - posts
              - events
            limit: 10       

  configuration:
    icon: cog
    columns: 
      - width: 1/3
        sections:
          general1:
            type: fields
            fields:
              menu:
                label: Menu
                type: pages
      
      - width: 1/3
        sections:
          general2:
            type: fields
            fields:
              logo:
                label: Logo
                translate: false
                type: files
                max: 1            
              placeholderImage:
                label: Placeholder Image
                help: This image will be used as a default image, for when no image is uploaded to an event or a page.
                translate: false
                type: files
                max: 1
                size: small

        
      - width: 1/3
        sections:
          general3:
            type: fields
            fields:
              socialLinks:
                label: Social Links
                type: structure
                translate: false
                fields:
                  name:
                    label: Social Network Name
                    type: text
                  url:
                    label: URL
                    type: url
                  icon:
                    label: Icon
                    type: select
                    options:
                      facebook: Facebook
                      instagram: Instagram
                      youtube: YouTube            
          generateStaticSite:
            label: Generate Static Site
            type: pages
            templates: 
              - static-site-generator
            help: admin use only
              


      
