title: Content

tabs:
  events:
    icon: layers
    columns: 
      - width: 2/3
        sections:
          events:
            type: pages
            headline: All Events
            status: all
            templates:
              - event
            sortBy: date desc
            limit: 20
            info: "{{ page.date }}"  # Display the date in a readable format
            query: site.find("events").children().listed().filterBy('recurrence', 'none')

      - width: 1/3
        sections:
          recurringEvents:
            type: pages
            headline: Recurring Events
            status: all
            templates:
              - event
            sortBy: date desc
            limit: 20
            info: "{{ page.date }}"  # Display the date in a readable format
            query: site.find("events").children().listed().filterBy('recurrence', '!=', 'none')        

  pages:
    label: Posts & Pages
    icon: page
    columns: 
      - width: 2/3
        sections:
          posts:
            type: pages
            parent: site.find("posts")  # get posts from parent page
            templates: 
              - post
            limit: 10

      - width: 1/3
        sections:   
          pages:
            type: pages
            templates: 
              - default
              - home
            limit: 10  
          dynamicPages:
            type: pages
            label: Dynamic Pages
            templates: 
              - posts
              - events
            limit: 10       

  configuration:
    icon: cog
    columns: 
      - width: 2/3
        
      - width: 1/3
        sections:
          general:
            type: fields
            fields:
              menu:
                label: Menu
                type: pages
              logo:
                label: Logo
                translate: false
                type: files
                max: 1
              placeholderImage:
                label: Placeholder Image
                help: This image will be used as a default image, for when no image is uploaded to an event or a page.
                translate: false
                type: files
                max: 1
                size: small
              socialLinks:
                label: Social Links
                type: structure
                translate: false
                fields:
                  name:
                    label: Social Network Name
                    type: text
                  url:
                    label: URL
                    type: url
                  icon:
                    label: Icon
                    type: select
                    options:
                      facebook: Facebook
                      instagram: Instagram
                      youtube: YouTube    
          generateStaticSite:
            label: Generate Static Site
            type: pages
            templates: 
              - static-site-generator
            help: admin use only
              


      
